//
//  ListView+Import.swift
//  CarbonAtlas
//
//  Created by Matthew Danbury on 4/26/22.
//

import SwiftUI

extension ListView {
    func importHowBadAreBananas() -> [Footprint] {
        [
            Footprint(data: Footprint.Data(name: "A Spam Email Picked up by Your Filters", notes: "", possibleImageName: "email", c02e: "0.03")),
            Footprint(data: Footprint.Data(name: "A Short Email Going from Phone to Phone", notes: "", possibleImageName: "email", c02e: "0.2")),
            Footprint(data: Footprint.Data(name: "One Pint of Tap Water", notes: "", possibleImageName: "tap water", c02e: "0.2")),
            Footprint(data: Footprint.Data(name: "A Short Email Sent from Laptop to Laptop", notes: "", possibleImageName: "email", c02e: "0.3")),
            Footprint(data: Footprint.Data(name: "A Google Search", notes: "", possibleImageName: "google search", c02e: "0.5")),
            Footprint(data: Footprint.Data(name: "A Text Message", notes: "", possibleImageName: "text", c02e: "0.8")),
            Footprint(data: Footprint.Data(name: "Drying your Hands with the Dyson Airblade", notes: "", possibleImageName: "hand dryer", c02e: "2")),
            Footprint(data: Footprint.Data(name: "An Hour-Long Zoom Meeting on the 2020 13-inch MacBook Pro", notes: "", possibleImageName: "zoom call", c02e: "2")),
            Footprint(data: Footprint.Data(name: "A Lightweight Plastic Bag", notes: "", possibleImageName: "plastic bag", c02e: "3")),
            Footprint(data: Footprint.Data(name: "Opening your front door on a cold winter's day", notes: "", possibleImageName: "door", c02e: "3")),
            Footprint(data: Footprint.Data(name: "5 Minutes of Web Browsing from a Smartphone", notes: "", possibleImageName: "google search", c02e: "5.6")),
            Footprint(data: Footprint.Data(name: "Travelling a mile on a full 90-seat electric bus in the UK", notes: "", possibleImageName: "bus", c02e: "6")),
            Footprint(data: Footprint.Data(name: "5 Minutes of Web Browsing from a Laptop", notes: "", possibleImageName: "google search", c02e: "8.2")),
            Footprint(data: Footprint.Data(name: "1 kWh of electricity from the Icelandic grid.", notes: "", possibleImageName: "electricity", c02e: "9")),
            Footprint(data: Footprint.Data(name: "Drying Your Hands With One Paper Towel", notes: "", possibleImageName: "hand dryer", c02e: "10")),
            Footprint(data: Footprint.Data(name: "An Hour-Long Zoom Meeting on an Averagely Efficient Laptop", notes: "", possibleImageName: "zoom call", c02e: "10")),
            Footprint(data: Footprint.Data(name: "A Heavyweight Plastic Bag", notes: "", possibleImageName: "plastic bag", c02e: "10")),
            Footprint(data: Footprint.Data(name: "Drying Your Hands With a Standard Electric Dryer", notes: "", possibleImageName: "hand dryer", c02e: "11")),
            Footprint(data: Footprint.Data(name: "A Lightweight, Recycled Paper Bag", notes: "", possibleImageName: "paper bag", c02e: "12")),
            Footprint(data: Footprint.Data(name: "An aluminum takeout container with lid, washed and recyled.", notes: "", possibleImageName: "aluminum", c02e: "13")),
            Footprint(data: Footprint.Data(name: "Ironing a Shirt", notes: "", possibleImageName: "iron shirt", c02e: "14")),
            Footprint(data: Footprint.Data(name: "Travelling a Mile on an Electric Bike You Ride Regularly", notes: "", possibleImageName: "electric bike", c02e: "15")),
            Footprint(data: Footprint.Data(name: "A Long Email That Takes 10 Minutes to Write and 3 Minutes to Read, Sent from Laptop to Laptop", notes: "", possibleImageName: "email", c02e: "17")),
            Footprint(data: Footprint.Data(name: "Travelling a mile on a French train powered by nulcear-generated electricity", notes: "", possibleImageName: "train", c02e: "22")),
            Footprint(data: Footprint.Data(name: "A cup of tea.", notes: "", possibleImageName: "tea", c02e: "22")),
            Footprint(data: Footprint.Data(name: "Using the internet's servers and networks for an hour.", notes: "", possibleImageName: "server", c02e: "22")),
            Footprint(data: Footprint.Data(name: "An plastic takeout container with lid, washed and recyled.", notes: "", possibleImageName: "plastic container", c02e: "25")),
            Footprint(data: Footprint.Data(name: "An Email That Takes You 10 Minutes to Write, Sent to 100 People, 99 of Whom Take 3 Seconds to Realize They Should Ignore It and One of Whom Reads It", notes: "", possibleImageName: "email", c02e: "26")),
            Footprint(data: Footprint.Data(name: "Travelling a mile squeezed into a minibus in La Paz, Bolivia", notes: "", possibleImageName: "bus", c02e: "26")),
            Footprint(data: Footprint.Data(name: "100g Carrots, Local and Seasonal", notes: "", possibleImageName: "carrots", c02e: "28")),
            Footprint(data: Footprint.Data(name: "An Apple, Local and Seasonal", notes: "", possibleImageName: "apple", c02e: "32")),
            Footprint(data: Footprint.Data(name: "1 kWh of heat from a solar heating panel.", notes: "", possibleImageName: "solar", c02e: "30")),
            Footprint(data: Footprint.Data(name: "1 kWh of heat from a photovoltaic panel with heat pump.", notes: "", possibleImageName: "solar", c02e: "30")),
            Footprint(data: Footprint.Data(name: "Boiling a Litre of Water With an Electric Kettle", notes: "", possibleImageName: "electric kettle", c02e: "40")),
            Footprint(data: Footprint.Data(name: "Getting your groceries delivered by electric bike.", notes: "", possibleImageName: "supermarket delivery", c02e: "40")),
            Footprint(data: Footprint.Data(name: "Travelling a mile on an half-full diesel hybrid bus.", notes: "", possibleImageName: "bus", c02e: "46")),
            Footprint(data: Footprint.Data(name: "A cup of tea with soy milk.", notes: "", possibleImageName: "tea milk", c02e: "47")),
            Footprint(data: Footprint.Data(name: "A cup of instant coffee.", notes: "", possibleImageName: "coffee", c02e: "49")),
            Footprint(data: Footprint.Data(name: "Boiling a litre of water with a kettle over low heat on a gas stove.", notes: "", possibleImageName: "kettle stove", c02e: "50")),
            Footprint(data: Footprint.Data(name: "Cycling a mile on a bike you ride regularly, feuled by bananas", notes: "", possibleImageName: "cycling", c02e: "50")),
            Footprint(data: Footprint.Data(name: "A Reusable Supermarket Bag", notes: "", possibleImageName: "reusable bag", c02e: "50")),
            Footprint(data: Footprint.Data(name: "An Hour-Long Zoom Meeting on a Desktop Computer with Monitor", notes: "", possibleImageName: "zoom call", c02e: "50")),
            Footprint(data: Footprint.Data(name: "A 3 minute shower using an aerated showerhead and an efficient gas boiler.", notes: "", possibleImageName: "shower", c02e: "55")),
            Footprint(data: Footprint.Data(name: "200g of raw potatoes, local.", notes: "", possibleImageName: "raw potato", c02e: "56")),
            Footprint(data: Footprint.Data(name: "A reusable diaper, washed at 60 celsius with other clothes, line dried, and passed on to a second child.", notes: "", possibleImageName: "diaper", c02e: "56")),
            Footprint(data: Footprint.Data(name: "Travelling a mile on the London Underground tube train", notes: "", possibleImageName: "train", c02e: "68")),
            Footprint(data: Footprint.Data(name: "Travelling a mile on light rail or tram", notes: "", possibleImageName: "tram", c02e: "72")),
            Footprint(data: Footprint.Data(name: "A freeze pop from the supermarket.", notes: "", possibleImageName: "popsicle", c02e: "70")),
            Footprint(data: Footprint.Data(name: "A cup of tea with cow's milk.", notes: "", possibleImageName: "tea milk", c02e: "71")),
            Footprint(data: Footprint.Data(name: "Travelling a mile on an intercity train, standard class.", notes: "", possibleImageName: "train", c02e: "80")),
            Footprint(data: Footprint.Data(name: "Cycling a mile on a bike you ride regularly, feuled by cearal with cow's milk", notes: "", possibleImageName: "cycling", c02e: "80")),
            Footprint(data: Footprint.Data(name: "A Fashion Bag Made from Virgin Paper", notes: "", possibleImageName: "fashion bag", c02e: "80")),
            Footprint(data: Footprint.Data(name: "An Apple, Shipped and Seasonal", notes: "", possibleImageName: "apple", c02e: "80")),
            Footprint(data: Footprint.Data(name: "100g Baby Carrots, Local and Seasonal", notes: "", possibleImageName: "carrots", c02e: "83")),
            Footprint(data: Footprint.Data(name: "Walking through big electric doors opening into a large stairwell on a cold windy day.", notes: "", possibleImageName: "big door", c02e: "83")),
            Footprint(data: Footprint.Data(name: "A cup of drip coffee", notes: "", possibleImageName: "coffee", c02e: "87")),
            Footprint(data: Footprint.Data(name: "100g Carrots Shipped Within Europe", notes: "", possibleImageName: "carrots", c02e: "90")),
            Footprint(data: Footprint.Data(name: "1 kWh of heat from a photovoltaic panel without heat pump.", notes: "", possibleImageName: "solar", c02e: "90")),
            Footprint(data: Footprint.Data(name: "200g of local potatoes, boiled gently with the lid on.", notes: "", possibleImageName: "boiled potato", c02e: "106")),
            Footprint(data: Footprint.Data(name: "A banana.", notes: "", possibleImageName: "banana", c02e: "110")),
            Footprint(data: Footprint.Data(name: "A bowl of porridge made with water.", notes: "", possibleImageName: "porridge", c02e: "110")),
            Footprint(data: Footprint.Data(name: "A disposable cup.", notes: "", possibleImageName: "paper cup", c02e: "110")),
            Footprint(data: Footprint.Data(name: "Snapdragon flowers, grown and sold locally", notes: "", possibleImageName: "snapdragon", c02e: "110")),
            Footprint(data: Footprint.Data(name: "Boiling a litre of water in a saucepan with no lid on a gas stove.", notes: "", possibleImageName: "water pot", c02e: "115")),
            Footprint(data: Footprint.Data(name: "A disposable diaper.", notes: "", possibleImageName: "diaper", c02e: "130")),
            Footprint(data: Footprint.Data(name: "A Pizza Box.", notes: "", possibleImageName: "pizza box", c02e: "130")),
            Footprint(data: Footprint.Data(name: "An aluminum takeout container that ends up in the landfill", notes: "", possibleImageName: "aluminum", c02e: "130")),
            Footprint(data: Footprint.Data(name: "A day's protein from 250g mixed nuts.", notes: "", possibleImageName: "nuts", c02e: "130")),
            Footprint(data: Footprint.Data(name: "Steaming an hour of video on the 2020 13-inch MacBook Pro", notes: "", possibleImageName: "macbook pro", c02e: "132")),
            Footprint(data: Footprint.Data(name: "An Orange", notes: "", possibleImageName: "orange", c02e: "150")),
            Footprint(data: Footprint.Data(name: "Getting your groceries delivered by electric van.", notes: "", possibleImageName: "supermarket delivery", c02e: "150")),
            Footprint(data: Footprint.Data(name: "Travelling a mile on an intercity train, first class.", notes: "", possibleImageName: "train", c02e: "160")),
            Footprint(data: Footprint.Data(name: "A 5 minute shower in a 5kW electric shower.", notes: "", possibleImageName: "shower", c02e: "160")),
            Footprint(data: Footprint.Data(name: "A reusable diaper, tumbled-dried and washed at 90 celsius.", notes: "", possibleImageName: "diaper", c02e: "165")),
            Footprint(data: Footprint.Data(name: "Watching an hour of television on a 55-inch LED TV", notes: "", possibleImageName: "tv", c02e: "170")),
            Footprint(data: Footprint.Data(name: "Driving a mile in a mid-sized electric car.", notes: "", possibleImageName: "driving", c02e: "180")),
            Footprint(data: Footprint.Data(name: "Cycling a mile on a bike you ride regularly, feuled by bacon", notes: "", possibleImageName: "cycling", c02e: "200")),
            Footprint(data: Footprint.Data(name: "Taking a modest bath heated by solar energy", notes: "", possibleImageName: "bath", c02e: "200")),
            Footprint(data: Footprint.Data(name: "Steaming an hour of video on a 55-inch LED TV", notes: "", possibleImageName: "tv", c02e: "206")),
            Footprint(data: Footprint.Data(name: "A day's protein from 800g of peas", notes: "", possibleImageName: "peas", c02e: "220")),
            Footprint(data: Footprint.Data(name: "Watching an hour of television on a 42-inch plasma TV", notes: "", possibleImageName: "tv", c02e: "237")),
            Footprint(data: Footprint.Data(name: "200g of shipped potatoes, boiled gently with the lid on.", notes: "", possibleImageName: "boiled potato", c02e: "240")),
            Footprint(data: Footprint.Data(name: "A 5 minute shower in a typical 8kW electric shower.", notes: "", possibleImageName: "shower", c02e: "250")),
            Footprint(data: Footprint.Data(name: "1 kWh of heat from a modern gas boiler.", notes: "", possibleImageName: "heat", c02e: "250")),
            Footprint(data: Footprint.Data(name: "250g Asparagus, local, seasonal.", notes: "", possibleImageName: "asparagus", c02e: "250")),
            Footprint(data: Footprint.Data(name: "A 10g letter on recycled paper, recycled by the recipient.", notes: "", possibleImageName: "mail", c02e: "280")),
            Footprint(data: Footprint.Data(name: "An Oat Milk Latte", notes: "", possibleImageName: "latte", c02e: "288")),
            Footprint(data: Footprint.Data(name: "Driving a mile in a smart car at 60mph.", notes: "", possibleImageName: "driving", c02e: "290")),
            Footprint(data: Footprint.Data(name: "An Apple, Shipped, Out-Of Season, Frozen", notes: "", possibleImageName: "apple", c02e: "290")),
            Footprint(data: Footprint.Data(name: "A Soy Milk Latte", notes: "", possibleImageName: "latte", c02e: "308")),
            Footprint(data: Footprint.Data(name: "Cycling a mile on a bike you ride regularly, feuled by cheeseburgers", notes: "", possibleImageName: "cycling", c02e: "310")),
            Footprint(data: Footprint.Data(name: "A weekday newspaper, recycled.", notes: "", possibleImageName: "newspaper", c02e: "310")),
            Footprint(data: Footprint.Data(name: "A load of laundry washed at 30 celsius and line dried", notes: "", possibleImageName: "line dry", c02e: "330")),
            Footprint(data: Footprint.Data(name: "200g of shipped potatoes, boiled furiously with the lid off.", notes: "", possibleImageName: "boiled potato", c02e: "340")),
            Footprint(data: Footprint.Data(name: "1 kWh of electricity from the UK grid.", notes: "", possibleImageName: "electricity", c02e: "340")),
            Footprint(data: Footprint.Data(name: "Getting food delivered by scooter.", notes: "", possibleImageName: "supermarket delivery", c02e: "340")),
            Footprint(data: Footprint.Data(name: "A 25g letter on virgin paper that ends up in a landfill.", notes: "", possibleImageName: "mail", c02e: "350")),
            Footprint(data: Footprint.Data(name: "Doing the dishes, using warm water sparingly.", notes: "", possibleImageName: "dishes", c02e: "360")),
            Footprint(data: Footprint.Data(name: "A 4oz vegan bean burger", notes: "", possibleImageName: "bean burger", c02e: "360")),
            Footprint(data: Footprint.Data(name: "1 kWh of heat from an old gas boiler.", notes: "", possibleImageName: "heat", c02e: "400")),
            Footprint(data: Footprint.Data(name: "Desalinating 1000 litres of brackish water via solar-powered reverse osmosis", notes: "", possibleImageName: "desalinate", c02e: "400")),
            Footprint(data: Footprint.Data(name: "A litre of bottled water.", notes: "", possibleImageName: "water bottle", c02e: "400")),
            Footprint(data: Footprint.Data(name: "A paperback book, printed on recyled paper, if every copy gets sold.", notes: "", possibleImageName: "book", c02e: "400")),
            Footprint(data: Footprint.Data(name: "A day's protein from 625g of lentils or chickpeas", notes: "", possibleImageName: "lentils", c02e: "400")),
            Footprint(data: Footprint.Data(name: "Getting your groceries delivered by diesel van.", notes: "", possibleImageName: "supermarket delivery", c02e: "450")),
            Footprint(data: Footprint.Data(name: "A bowl of porridge made with soy milk.", notes: "", possibleImageName: "porridge", c02e: "450")),
            Footprint(data: Footprint.Data(name: "A bowl of porridge made with half cow's milk, half water.", notes: "", possibleImageName: "porridge", c02e: "450")),
            Footprint(data: Footprint.Data(name: "Toilet paper from recycled paper.", notes: "", possibleImageName: "toilet paper", c02e: "450")),
            Footprint(data: Footprint.Data(name: "Running the dishwasher at 50 celsius", notes: "", possibleImageName: "dishes", c02e: "470")),
            Footprint(data: Footprint.Data(name: "200g Fresh Mackerel, caught and sold locally.", notes: "", possibleImageName: "fish", c02e: "480")),
            Footprint(data: Footprint.Data(name: "250g of strawberries, local and seasonal.", notes: "", possibleImageName: "strawberries", c02e: "490")),
            Footprint(data: Footprint.Data(name: "Taking a modest bath heated by an efficient gas boiler.", notes: "", possibleImageName: "bath", c02e: "500")),
            Footprint(data: Footprint.Data(name: "A frozen dairy treat from an icecream truck.", notes: "", possibleImageName: "icecream", c02e: "500")),
            Footprint(data: Footprint.Data(name: "A pint of oat milk", notes: "", possibleImageName: "milk", c02e: "510")),
            Footprint(data: Footprint.Data(name: "A pint of soy milk", notes: "", possibleImageName: "milk", c02e: "510")),
            Footprint(data: Footprint.Data(name: "Driving a mile in an average 36mpg UK car.", notes: "", possibleImageName: "driving", c02e: "530")),
            Footprint(data: Footprint.Data(name: "A load of laundry washed at 40 celsius and line dried", notes: "", possibleImageName: "line dry", c02e: "540")),
            Footprint(data: Footprint.Data(name: "A cow's milk latte", notes: "", possibleImageName: "latte", c02e: "552")),
            Footprint(data: Footprint.Data(name: "A load of laundry washed at 60 celsius and line dried", notes: "", possibleImageName: "laundry", c02e: "590")),
            Footprint(data: Footprint.Data(name: "1kg of trash headed to the landfill", notes: "", possibleImageName: "rubbish", c02e: "590")),
            Footprint(data: Footprint.Data(name: "Running the dishwasher at 65 celsius", notes: "", possibleImageName: "dishes", c02e: "600")),
            Footprint(data: Footprint.Data(name: "A loaf of bread from a local bakery", notes: "", possibleImageName: "bread", c02e: "630")),
            Footprint(data: Footprint.Data(name: "A 4oz vegan bean burger with cheese", notes: "", possibleImageName: "bean burger", c02e: "630")),
            Footprint(data: Footprint.Data(name: "1 kWh of electricity from the US grid.", notes: "", possibleImageName: "electricity", c02e: "650")),
            Footprint(data: Footprint.Data(name: "A pint of locally brewed beer at a bar.", notes: "", possibleImageName: "beer", c02e: "650")),
            Footprint(data: Footprint.Data(name: "Toilet paper from virgin paper.", notes: "", possibleImageName: "toilet paper", c02e: "730")),
            Footprint(data: Footprint.Data(name: "Spending a dollar at the supermarket.", notes: "", possibleImageName: "supermarket", c02e: "750")),
            Footprint(data: Footprint.Data(name: "250g of strawberries, frozen.", notes: "", possibleImageName: "strawberries", c02e: "770")),
            Footprint(data: Footprint.Data(name: "A pint of locally botttled beer from the store.", notes: "", possibleImageName: "beer", c02e: "780")),
            Footprint(data: Footprint.Data(name: "A bowl of porridge made with cow's milk.", notes: "", possibleImageName: "porridge", c02e: "800")),
            Footprint(data: Footprint.Data(name: "200g fresh cod, caught and sold locally", notes: "", possibleImageName: "fish", c02e: "880")),
            Footprint(data: Footprint.Data(name: "A pint of imported beer at a bar.", notes: "", possibleImageName: "beer", c02e: "910")),
            Footprint(data: Footprint.Data(name: "1 kWh of electricity from the Chinese grid.", notes: "", possibleImageName: "electricity", c02e: "980")),
            Footprint(data: Footprint.Data(name: "A 15 minute shower in a 11kW electric shower.", notes: "", possibleImageName: "shower", c02e: "1000")),
            Footprint(data: Footprint.Data(name: "A full bath heated by an efficient gas boiler.", notes: "", possibleImageName: "bath", c02e: "1000")),
            Footprint(data: Footprint.Data(name: "A regular paperback book (60 percent of copies printed are sold).", notes: "", possibleImageName: "book", c02e: "1000")),
            Footprint(data: Footprint.Data(name: "A pint of imported bottled beer from the store.", notes: "", possibleImageName: "beer", c02e: "1000")),
            Footprint(data: Footprint.Data(name: "A 10-inch vegan pizza.", notes: "", possibleImageName: "pizza", c02e: "1000")),
            Footprint(data: Footprint.Data(name: "Going out to get groceries yourself in an average petrol car", notes: "", possibleImageName: "supermarket delivery", c02e: "1000")),
            Footprint(data: Footprint.Data(name: "A loaf of bread, transported by road", notes: "", possibleImageName: "bread", c02e: "1000")),
            Footprint(data: Footprint.Data(name: "1 kWh of electricity from the Australian grid.", notes: "", possibleImageName: "electricity", c02e: "1005")),
            Footprint(data: Footprint.Data(name: "Driving a mile in a new Range Rover Sport at 90mph.", notes: "", possibleImageName: "driving", c02e: "1260")),
            Footprint(data: Footprint.Data(name: "1kg of large tomatoes, grown locally in season", notes: "", possibleImageName: "tomato", c02e: "1300")),
            Footprint(data: Footprint.Data(name: "A 10-inch Margherita Pizza", notes: "", possibleImageName: "pizza", c02e: "1400")),
            Footprint(data: Footprint.Data(name: "A pair of Crocs", notes: "", possibleImageName: "crocs", c02e: "1500")),
            Footprint(data: Footprint.Data(name: "A full bath heated by an electricity.", notes: "", possibleImageName: "bath", c02e: "1600")),
            Footprint(data: Footprint.Data(name: "250g of goat's cheese", notes: "", possibleImageName: "cheese", c02e: "1600")),
            Footprint(data: Footprint.Data(name: "A day's protein from two and a half pints of milk.", notes: "", possibleImageName: "milk", c02e: "1600")),
            Footprint(data: Footprint.Data(name: "Spending a dollar on solar panels", notes: "", possibleImageName: "solar", c02e: "-1650")),
            Footprint(data: Footprint.Data(name: "A bottle of wine transported by road", notes: "", possibleImageName: "wine", c02e: "1650")),
            Footprint(data: Footprint.Data(name: "200g fresh trout, caught and sold locally", notes: "", possibleImageName: "fish", c02e: "1700")),
            Footprint(data: Footprint.Data(name: "Bouquet of 15 different flowers, grown outdoors and sold locally.", notes: "", possibleImageName: "flowers", c02e: "1700")),
            Footprint(data: Footprint.Data(name: "1kg PET plastic bottles, made from recycled material and recycled again after being used", notes: "", possibleImageName: "plastic bottle", c02e: "1700")),
            Footprint(data: Footprint.Data(name: "A pint of cow's milk", notes: "", possibleImageName: "milk", c02e: "1800")),
            Footprint(data: Footprint.Data(name: "200g canned tuna", notes: "", possibleImageName: "tuna can", c02e: "1900")),
            Footprint(data: Footprint.Data(name: "A weekend paper with supplements, recycled.", notes: "", possibleImageName: "newspaper", c02e: "1900")),
            Footprint(data: Footprint.Data(name: "A paperback book printed on thick virgin paper and only half the copies sell.", notes: "", possibleImageName: "book", c02e: "2000")),
            Footprint(data: Footprint.Data(name: "A small catalogue or magazine that ends up in a landfill.", notes: "", possibleImageName: "mail", c02e: "2000")),
            Footprint(data: Footprint.Data(name: "A box of six large eggs", notes: "", possibleImageName: "eggs", c02e: "2000")),
            Footprint(data: Footprint.Data(name: "A load of laundry washed at 40 celsius and tumble dried", notes: "", possibleImageName: "laundry", c02e: "2000")),
            Footprint(data: Footprint.Data(name: "A day's protein from seven large eggs", notes: "", possibleImageName: "eggs", c02e: "2100")),
            Footprint(data: Footprint.Data(name: "A 10-inch Pepperoni Pizza", notes: "", possibleImageName: "pizza", c02e: "2200")),
            Footprint(data: Footprint.Data(name: "A 10-inch Four-Cheese Pizza", notes: "", possibleImageName: "pizza", c02e: "2200")),
            Footprint(data: Footprint.Data(name: "Desalinating 1000 litres of seawater via reverse osmosis and conventional media filtration.", notes: "", possibleImageName: "desalinate", c02e: "2300")),
            Footprint(data: Footprint.Data(name: "Spending a dollar on gas for your car.", notes: "", possibleImageName: "gas", c02e: "2400")),
            Footprint(data: Footprint.Data(name: "A single rose grown in a greenhouse or air freighted from Kenya", notes: "", possibleImageName: "flowers", c02e: "2400")),
            Footprint(data: Footprint.Data(name: "Travelling a mile on a rural double-decker bus shared with just the driver.", notes: "", possibleImageName: "bus", c02e: "2500")),
            Footprint(data: Footprint.Data(name: "A day's protein from 180g of chicken", notes: "", possibleImageName: "chicken", c02e: "2800")),
            Footprint(data: Footprint.Data(name: "A 10-inch Meat Lover's Pizza", notes: "", possibleImageName: "pizza", c02e: "2800")),
            Footprint(data: Footprint.Data(name: "250g of cheddar cheese", notes: "", possibleImageName: "cheese", c02e: "3000")),
            Footprint(data: Footprint.Data(name: "Doing the dishes by hand with extravagent use of water", notes: "", possibleImageName: "dishes", c02e: "3000")),
            Footprint(data: Footprint.Data(name: "Spending a dollar paying your electricity bill.", notes: "", possibleImageName: "electricity", c02e: "3000")),
            Footprint(data: Footprint.Data(name: "1kg of rice, efficiently produced", notes: "", possibleImageName: "rice", c02e: "3000")),
            Footprint(data: Footprint.Data(name: "Bed and brekfast in a nice hotel that takes its footprint seriously.", notes: "", possibleImageName: "b and b", c02e: "3000")),
            Footprint(data: Footprint.Data(name: "A 4oz cheeseburger", notes: "", possibleImageName: "burger", c02e: "3200")),
            Footprint(data: Footprint.Data(name: "1kg polystyrene made from virgin materials", notes: "", possibleImageName: "polystyrene", c02e: "3400")),
            Footprint(data: Footprint.Data(name: "250g of strawberries, grown out of season or air freighted.", notes: "", possibleImageName: "strawberries", c02e: "3650")),
            Footprint(data: Footprint.Data(name: "A day's protein from 200g of pork", notes: "", possibleImageName: "pork", c02e: "3800")),
            Footprint(data: Footprint.Data(name: "1kg of rice, avereage production", notes: "", possibleImageName: "rice", c02e: "4000")),
            Footprint(data: Footprint.Data(name: "Modest vegetarian takeout for four people.", notes: "", possibleImageName: "vegetarian", c02e: "4000")),
            Footprint(data: Footprint.Data(name: "1kg PET plastic bottles, made from virgin material", notes: "", possibleImageName: "plastic bottle", c02e: "4200")),
            Footprint(data: Footprint.Data(name: "200g fresh lobster, transported extensively by road", notes: "", possibleImageName: "lobster", c02e: "4500")),
            Footprint(data: Footprint.Data(name: "A weekend paper with supplements that ends up in the landfill.", notes: "", possibleImageName: "newspaper", c02e: "4700")),
            Footprint(data: Footprint.Data(name: "Cycling a mile on a bike you ride regularly, feuled by air-freighted asparagus", notes: "", possibleImageName: "cycling", c02e: "4700")),
            Footprint(data: Footprint.Data(name: "250g asparagus, air freighted", notes: "", possibleImageName: "asparagus", c02e: "4700")),
            Footprint(data: Footprint.Data(name: "250g of parmesan", notes: "", possibleImageName: "cheese", c02e: "4800")),
            Footprint(data: Footprint.Data(name: "1kg of baby plum tomatoes, grown locally in season", notes: "", possibleImageName: "tomato", c02e: "4900")),
            Footprint(data: Footprint.Data(name: "1kg PET plastic bottles, made from virgin material, incinerated after use", notes: "", possibleImageName: "plastic bottle", c02e: "5400")),
            Footprint(data: Footprint.Data(name: "Spending a dollar on a budget flight.", notes: "", possibleImageName: "flight", c02e: "5500")),
            Footprint(data: Footprint.Data(name: "An 8oz steak, reared locally", notes: "", possibleImageName: "steak", c02e: "5800")),
            Footprint(data: Footprint.Data(name: "Desalinating 1000 litres of seawater via reverse osmosis and conventional media filtration, using electricity from coal.", notes: "", possibleImageName: "desalinate", c02e: "6700")),
            Footprint(data: Footprint.Data(name: "1kg of rice, poorly produced with excessive fertiliser", notes: "", possibleImageName: "rice", c02e: "7100")),
            Footprint(data: Footprint.Data(name: "A pair of shoes made of synthetic material", notes: "", possibleImageName: "synthetic shoes", c02e: "8000")),
            Footprint(data: Footprint.Data(name: "A pair of pants made of polyester", notes: "", possibleImageName: "synthetic pants", c02e: "8000")),
            Footprint(data: Footprint.Data(name: "A day's protein from 200g of imported king prawns", notes: "", possibleImageName: "prawns", c02e: "9000")),
            Footprint(data: Footprint.Data(name: "One 25kg bag of 'green' cement alternative", notes: "", possibleImageName: "cement", c02e: "9000")),
            Footprint(data: Footprint.Data(name: "1kg of aluminium and copper waste headed to the landfill", notes: "", possibleImageName: "rubbish", c02e: "9100")),
            Footprint(data: Footprint.Data(name: "1kg of nylon", notes: "", possibleImageName: "nylon", c02e: "9100")),
            Footprint(data: Footprint.Data(name: "A day's protein from 200g of lamb", notes: "", possibleImageName: "lamb", c02e: "10000")),
            Footprint(data: Footprint.Data(name: "A pair of pants made of acrylics", notes: "", possibleImageName: "synthetic pants", c02e: "11000")),
            Footprint(data: Footprint.Data(name: "An average pair of shoes", notes: "", possibleImageName: "shoes", c02e: "11500")),
            Footprint(data: Footprint.Data(name: "A pair of shoes made of leather", notes: "", possibleImageName: "leather shoes", c02e: "15000")),
            Footprint(data: Footprint.Data(name: "Leaving a 5-watt low-energy bulb on for a year", notes: "", possibleImageName: "light bulb", c02e: "15000")),
            Footprint(data: Footprint.Data(name: "A congested 10 mile commute", notes: "", possibleImageName: "heavy traffic", c02e: "16000")),
            Footprint(data: Footprint.Data(name: "One 25kg bag of industrially trialled low-emission cement", notes: "", possibleImageName: "cement", c02e: "17000")),
            Footprint(data: Footprint.Data(name: "A weeks worth of groceries, vegan, no airfreight, and nothing goes to waste", notes: "", possibleImageName: "supermarket delivery", c02e: "17000")),
            Footprint(data: Footprint.Data(name: "An 8oz steak, reared on deforested land in Brazil", notes: "", possibleImageName: "steak", c02e: "17800")),
            Footprint(data: Footprint.Data(name: "A Year's Tap Water for a Typical UK Citizen", notes: "", possibleImageName: "tap water", c02e: "18000")),
            Footprint(data: Footprint.Data(name: "A pair of men's cotton jeans", notes: "", possibleImageName: "jeans", c02e: "19000")),
            Footprint(data: Footprint.Data(name: "Large takeout for four people with meat and or seafood.", notes: "", possibleImageName: "curry", c02e: "24000")),
            Footprint(data: Footprint.Data(name: "One 25kg bag of ordinary cement", notes: "", possibleImageName: "cement", c02e: "24000")),
            Footprint(data: Footprint.Data(name: "A day's protein from 190g of beef", notes: "", possibleImageName: "steak", c02e: "25000")),
            Footprint(data: Footprint.Data(name: "Caring for a pet goldfish for a year", notes: "", possibleImageName: "goldfish", c02e: "25000")),
            Footprint(data: Footprint.Data(name: "1kg organic cherry tomateoes greenhouse grown out of season.", notes: "", possibleImageName: "tomato", c02e: "28200")),
            Footprint(data: Footprint.Data(name: "Dinner, drinks, bed and brekfast in a hotel with average eco credentials.", notes: "", possibleImageName: "b and b", c02e: "30000")),
            Footprint(data: Footprint.Data(name: "A bouquet of 13 greenhouse-grown or airfrieghted roses and lillies", notes: "", possibleImageName: "flowers", c02e: "32300")),
            Footprint(data: Footprint.Data(name: "Desalinating 1000 litres of seawater via thermal desalination.", notes: "", possibleImageName: "desalinate", c02e: "34700")),
            Footprint(data: Footprint.Data(name: "A weeks worth of groceries, vegan, average", notes: "", possibleImageName: "supermarket delivery", c02e: "36000")),
            Footprint(data: Footprint.Data(name: "A 2kg leg of lamb", notes: "", possibleImageName: "lamb leg", c02e: "42000")),
            Footprint(data: Footprint.Data(name: "A weeks worth of groceries, vegetarian, average", notes: "", possibleImageName: "supermarket delivery", c02e: "46000")),
            Footprint(data: Footprint.Data(name: "A weeks worth of groceries, incuding meat", notes: "", possibleImageName: "supermarket delivery", c02e: "61000")),
            Footprint(data: Footprint.Data(name: "Using your smartphone one hour a day for a year", notes: "", possibleImageName: "text", c02e: "63000")),
            Footprint(data: Footprint.Data(name: "Using your smartphone 195 minutes a day for a year (the consumer average)", notes: "", possibleImageName: "text", c02e: "69000")),
            Footprint(data: Footprint.Data(name: "Night in a lavish hotel with no eco credentials.", notes: "", possibleImageName: "hotel", c02e: "75000")),
            Footprint(data: Footprint.Data(name: "A new 4mx4m carpet made of thin polyurethane with thin underlay.", notes: "", possibleImageName: "carpet", c02e: "76000")),
            Footprint(data: Footprint.Data(name: "Using your smartphone 10 hours a day for a year", notes: "", possibleImageName: "text", c02e: "86000")),
            Footprint(data: Footprint.Data(name: "A weeks worth of groceries, incuding meat and airfreight", notes: "", possibleImageName: "supermarket delivery", c02e: "88000")),
            Footprint(data: Footprint.Data(name: "Spending one dollar on a rainforest restoration project.", notes: "", possibleImageName: "rainforest", c02e: "-165000")),
            Footprint(data: Footprint.Data(name: "A 13-gallon tank of gas", notes: "", possibleImageName: "gas", c02e: "173000")),
            Footprint(data: Footprint.Data(name: "A 13-gallon tank of diesel", notes: "", possibleImageName: "gas", c02e: "196000")),
            Footprint(data: Footprint.Data(name: "The average Malawian's annual carbon footprint", notes: "", possibleImageName: "malawi", c02e: "200000")),
            Footprint(data: Footprint.Data(name: "A $700 necklace made of new Welsh gold", notes: "", possibleImageName: "gold", c02e: "230000")),
            Footprint(data: Footprint.Data(name: "A new 4mx4m carpet made of thick wool, polypropylene, or nylon with generous underlay.", notes: "", possibleImageName: "carpet", c02e: "290000")),
            Footprint(data: Footprint.Data(name: "Leaving a 100-watt incandescent bulb on for a year", notes: "", possibleImageName: "light bulb", c02e: "300000")),
            Footprint(data: Footprint.Data(name: "Caring for an average-sized pet cat for a year", notes: "", possibleImageName: "cat", c02e: "310000")),
            Footprint(data: Footprint.Data(name: "A new 13-inch MacBook Pro, 128GB Storage", notes: "", possibleImageName: "macbook pro", c02e: "326000")),
            Footprint(data: Footprint.Data(name: "A new 14-inch HP Chromebook 14g5", notes: "", possibleImageName: "chromebook", c02e: "329000")),
            Footprint(data: Footprint.Data(name: "A Cremation", notes: "", possibleImageName: "cremation", c02e: "410000")),
            Footprint(data: Footprint.Data(name: "A new 15-inch Dell Precision 5530 laptop with 256GB storage", notes: "", possibleImageName: "dell", c02e: "326000")),
            Footprint(data: Footprint.Data(name: "A tonne of recycled steel", notes: "", possibleImageName: "steel", c02e: "400000")),
            Footprint(data: Footprint.Data(name: "Disposable diapers for one child", notes: "", possibleImageName: "diaper", c02e: "490000")),
            Footprint(data: Footprint.Data(name: "A new 16-inch MacBook Pro, 1TB Storage", notes: "", possibleImageName: "macbook pro", c02e: "620000")),
            Footprint(data: Footprint.Data(name: "A $700 necklace made of gold and diamonds from Africa", notes: "", possibleImageName: "gold", c02e: "710000")),
            Footprint(data: Footprint.Data(name: "Caring for an average-sized pet dog for a year", notes: "", possibleImageName: "dog", c02e: "770000")),
            Footprint(data: Footprint.Data(name: "A Burial", notes: "", possibleImageName: "burial", c02e: "840000")),
            Footprint(data: Footprint.Data(name: "Annual energy savings from insulating your attic", notes: "", possibleImageName: "attic", c02e: "-1000000")),
            Footprint(data: Footprint.Data(name: "A mortgage, or using the financial services industry for a year", notes: "", possibleImageName: "finance", c02e: "1000000")),
            Footprint(data: Footprint.Data(name: "A hip replacement or knee surgery", notes: "", possibleImageName: "surgery", c02e: "1000000")),
            Footprint(data: Footprint.Data(name: "A tonne of steel manufactured with hydrogen instead of coal", notes: "", possibleImageName: "steel", c02e: "1100000")),
            Footprint(data: Footprint.Data(name: "Annual carbon savings from a 4kW domestic solar panel array", notes: "", possibleImageName: "solar", c02e: "-1200000")),
            Footprint(data: Footprint.Data(name: "A average tonne of steel (25 percent recycled)", notes: "", possibleImageName: "steel", c02e: "1800000")),
            Footprint(data: Footprint.Data(name: "A tonne of steel manufactured with coal", notes: "", possibleImageName: "steel", c02e: "2300000")),
            Footprint(data: Footprint.Data(name: "A heart bypass operation", notes: "", possibleImageName: "surgery", c02e: "2300000")),
            Footprint(data: Footprint.Data(name: "Caring for a pet Great Dane for a year", notes: "", possibleImageName: "great dane", c02e: "2500000")),
            Footprint(data: Footprint.Data(name: "A tonne of nitrogen fertiliser, made efficiently and spread sparingly", notes: "", possibleImageName: "fertilizer", c02e: "2700000")),
            Footprint(data: Footprint.Data(name: "A round-trip flight from London to Hong-Kong, economy class", notes: "", possibleImageName: "flight", c02e: "3500000")),
            Footprint(data: Footprint.Data(name: "Installing a 4kW domestic solar panel array", notes: "", possibleImageName: "solar", c02e: "5000000")),
            Footprint(data: Footprint.Data(name: "Totalling your car in a car accident", notes: "", possibleImageName: "car crash", c02e: "8000000")),
            Footprint(data: Footprint.Data(name: "The world average annual carbon footprint", notes: "", possibleImageName: "footprint", c02e: "7000000")),
            Footprint(data: Footprint.Data(name: "The average Chinese annual carbon footprint", notes: "", possibleImageName: "china", c02e: "8000000")),
            Footprint(data: Footprint.Data(name: "A new Ford Focus", notes: "", possibleImageName: "ford focus", c02e: "8000000")),
            Footprint(data: Footprint.Data(name: "A new Toyota Prius plug-in hybrid", notes: "", possibleImageName: "prius", c02e: "12000000")),
            Footprint(data: Footprint.Data(name: "A tonne of nitrogen fertiliser, made inefficiently and used in excess", notes: "", possibleImageName: "fertilizer", c02e: "12300000")),
            Footprint(data: Footprint.Data(name: "The average Briton's annual carbon footprint", notes: "", possibleImageName: "england", c02e: "13000000")),
            Footprint(data: Footprint.Data(name: "A round-trip flight from London to Hong-Kong, first class", notes: "", possibleImageName: "flight", c02e: "13900000")),
            Footprint(data: Footprint.Data(name: "A Business Meeting in Hong Kong where Two People Fly in from Europe", notes: "", possibleImageName: "business meeting", c02e: "20000000")),
            Footprint(data: Footprint.Data(name: "The average Australian's annual carbon footprint", notes: "", possibleImageName: "australia", c02e: "20000000")),
            Footprint(data: Footprint.Data(name: "The average North American's annual carbon footprint", notes: "", possibleImageName: "north america", c02e: "21000000")),
            Footprint(data: Footprint.Data(name: "A new Range Rover Sport", notes: "", possibleImageName: "range rover", c02e: "25000000")),
            Footprint(data: Footprint.Data(name: "Annual carbon savings from a 15-kW wind turbine", notes: "", possibleImageName: "wind turbine", c02e: "-25000000")),
            Footprint(data: Footprint.Data(name: "Installing a 15-kW wind turbine", notes: "", possibleImageName: "wind turbine", c02e: "30000000")),
            Footprint(data: Footprint.Data(name: "A car crash on a busy highway where two cars are totaled", notes: "", possibleImageName: "highway crash", c02e: "40000000")),
            Footprint(data: Footprint.Data(name: "Building a new four-bedroom house", notes: "", possibleImageName: "house", c02e: "53000000")),
            Footprint(data: Footprint.Data(name: "Annual carbon savings from a 100-kW wind turbine", notes: "", possibleImageName: "wind turbine", c02e: "134000000")),
            Footprint(data: Footprint.Data(name: "Installing a 100-kW wind turbine", notes: "", possibleImageName: "wind turbine", c02e: "134000000")),
            Footprint(data: Footprint.Data(name: "Having a child in the UK who grows up to be climate conscious.", notes: "", possibleImageName: "child", c02e: "210000000")),
            Footprint(data: Footprint.Data(name: "A Blue Origin New Shepard tourism spaceflight", notes: "", possibleImageName: "blue origin", c02e: "330000000")),
            Footprint(data: Footprint.Data(name: "A SpaceX Falcon 9 flight to the International Space Station", notes: "", possibleImageName: "spacex", c02e: "600000000")),
            Footprint(data: Footprint.Data(name: "Having a child in the UK who grows up to have todays average carbon footprint.", notes: "", possibleImageName: "child", c02e: "775000000")),
            Footprint(data: Footprint.Data(name: "Installing a 3MW wind turbine", notes: "", possibleImageName: "wind turbine", c02e: "1046000000")),
            Footprint(data: Footprint.Data(name: "Annual carbon savings from a 3MW wind turbine", notes: "", possibleImageName: "wind turbine", c02e: "4076000000")),
            Footprint(data: Footprint.Data(name: "Having a child in the UK who grows up to be wealthy and carbon-careless.", notes: "", possibleImageName: "child", c02e: "5000000000")),
            Footprint(data: Footprint.Data(name: "A Space Shuttle flight", notes: "", possibleImageName: "space shuttle", c02e: "7060000000")),
            Footprint(data: Footprint.Data(name: "The first flight to the moon, 1969", notes: "", possibleImageName: "moon", c02e: "10300000000")),
            Footprint(data: Footprint.Data(name: "Volcanic emissions from Mount Etna in a quiet year.", notes: "", possibleImageName: "mt etna", c02e: "1000000000000")),
            Footprint(data: Footprint.Data(name: "The Football World Cup, Russia 2018", notes: "", possibleImageName: "world cup", c02e: "2200000000000")),
            Footprint(data: Footprint.Data(name: "The Football World Cup, Brazil 2014", notes: "", possibleImageName: "world cup", c02e: "2700000000000")),
            Footprint(data: Footprint.Data(name: "The Football World Cup, South Africa 2010", notes: "", possibleImageName: "world cup", c02e: "2800000000000")),
            Footprint(data: Footprint.Data(name: "The Holuhraun eruption, Iceland 2014", notes: "", possibleImageName: "volcano", c02e: "5000000000000")),
            Footprint(data: Footprint.Data(name: "A new coal mine", notes: "", possibleImageName: "coal mine", c02e: "8400000000000")),
            Footprint(data: Footprint.Data(name: "Total UK healthcare emissions each year.", notes: "", possibleImageName: "england", c02e: "31000000000000")),
            Footprint(data: Footprint.Data(name: "The Mt. Pinatubo eruption, Philippines 1991", notes: "", possibleImageName: "volcano", c02e: "42000000000000")),
            Footprint(data: Footprint.Data(name: "Bitcoin, 2019", notes: "", possibleImageName: "bitcoin", c02e: "46000000000000")),
            Footprint(data: Footprint.Data(name: "All cryptocurrencies, 2019", notes: "", possibleImageName: "crypto", c02e: "68000000000000")),
            Footprint(data: Footprint.Data(name: "The world's data centers, 2020", notes: "", possibleImageName: "data center", c02e: "160000000000000")),
            Footprint(data: Footprint.Data(name: "US military operations in 2019", notes: "", possibleImageName: "military", c02e: "200000000000000")),
            Footprint(data: Footprint.Data(name: "The Iraq War, 2003-2019", notes: "", possibleImageName: "iraq war", c02e: "400000000000000")),
            Footprint(data: Footprint.Data(name: "The UK's emissions within its borders", notes: "", possibleImageName: "england", c02e: "435000000000000")),
            Footprint(data: Footprint.Data(name: "Global mobile phone usage each year.", notes: "", possibleImageName: "text", c02e: "690000000000000")),
            Footprint(data: Footprint.Data(name: "The UK's carbon footprint, including imports", notes: "", possibleImageName: "england", c02e: "840000000000000")),
            Footprint(data: Footprint.Data(name: "The 2019 Australian bushfires", notes: "", possibleImageName: "wildfire", c02e: "923000000000000")),
            Footprint(data: Footprint.Data(name: "The world's computers and information technology", notes: "", possibleImageName: "data center", c02e: "1400000000000000")),
            Footprint(data: Footprint.Data(name: "The annual global military bootprint", notes: "", possibleImageName: "military", c02e: "3300000000000000")),
            Footprint(data: Footprint.Data(name: "Global Wildfires in 2019", notes: "", possibleImageName: "wild fire", c02e: "8600000000000000")),
            Footprint(data: Footprint.Data(name: "Global black carbon (soot) emissions per year", notes: "", possibleImageName: "soot", c02e: "9000000000000000")),
            Footprint(data: Footprint.Data(name: "Global deforestation per year", notes: "", possibleImageName: "deforestation", c02e: "10000000000000000")),
            Footprint(data: Footprint.Data(name: "Global carbon dioxide emissions excluding deforestation in 2018", notes: "", possibleImageName: "emissions", c02e: "38000000000000000")),
            Footprint(data: Footprint.Data(name: "Global greenhouse gas emissions caused by humans in 2018", notes: "", possibleImageName: "globe", c02e: "56000000000000000"))
        ]
    }
}
